/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LocaleStringList = {
  _type: "localeStringList";
  fr?: Array<string>;
  nl?: Array<string>;
  en?: Array<string>;
};

export type LocaleText = {
  _type: "localeText";
  fr?: string;
  nl?: string;
  en?: string;
};

export type LocaleString = {
  _type: "localeString";
  fr: string;
  nl?: string;
  en?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }
        | {
            reference?: ArticleReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contact?: {
    street?: string;
    postalCode?: string;
    city?: string;
    region?: string;
    country?: string;
    phone?: string;
    email?: string;
  };
  legal?: {
    companyName?: string;
    enterpriseNumber?: string;
    vatNumber?: string;
    legalForm?: string;
  };
  socialLinks?: {
    instagram?: string;
    facebook?: string;
  };
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug: Slug;
  format: "breakfast" | "lunch" | "apero" | "buffet" | "seated";
  summary?: LocaleText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  courses?: Array<{
    title?: LocaleString;
    items?: LocaleStringList;
    _type: "course";
    _key: string;
  }>;
  pricePerPerson: number;
  priceNote?: LocaleString;
  minGuests: number;
  maxGuests?: number;
  leadTimeDays: number;
  includes?: LocaleStringList;
  excludes?: LocaleStringList;
  dietaryNote?: LocaleText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eventsImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coffeeImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  language: "fr" | "nl" | "en";
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: BlockContent;
  categories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  author: AuthorReference;
  publishedAt: string;
  featured?: boolean;
  seoTitle?: string;
  seoDescription?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LocaleStringList
  | LocaleText
  | LocaleString
  | ArticleReference
  | SanityImageAssetReference
  | BlockContent
  | SiteSettings
  | Menu
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | HomePage
  | Category
  | CategoryReference
  | AuthorReference
  | Article
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: articlesQuery
// Query: *[_type == "article" && language == $language] | order(publishedAt desc) {    _id,  title,  slug,  publishedAt,  excerpt,  mainImage,  author->{ name },  categories[]->{ title }}
export type ArticlesQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  author: {
    name: string;
  };
  categories: Array<{
    title: string;
  }>;
}>;

// Source: lib/sanity/queries.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && language == $language && slug.current == $slug][0] {    _id,  title,  slug,  publishedAt,  excerpt,  mainImage,  author->{ name },  categories[]->{ title },  body}
export type ArticleBySlugQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  author: {
    name: string;
  };
  categories: Array<{
    title: string;
  }>;
  body: BlockContent;
} | null;

// Source: lib/sanity/queries.ts
// Variable: articleSlugsQuery
// Query: *[_type == "article" && language == $language && defined(slug.current)]{  "slug": slug.current}
export type ArticleSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: lib/sanity/queries.ts
// Variable: menusQuery
// Query: *[_type == "menu"] | order(pricePerPerson asc) {    _id,  title,  slug,  format,  summary,  pricePerPerson,  priceNote,  minGuests,  maxGuests,  leadTimeDays,  includes,  excludes,  dietaryNote,  image,    courses[]{    _key,    title,    items  }}
export type MenusQueryResult = Array<{
  _id: string;
  title: LocaleString | null;
  slug: Slug;
  format: "apero" | "breakfast" | "buffet" | "lunch" | "seated";
  summary: LocaleText | null;
  pricePerPerson: number;
  priceNote: LocaleString | null;
  minGuests: number;
  maxGuests: number | null;
  leadTimeDays: number;
  includes: LocaleStringList | null;
  excludes: LocaleStringList | null;
  dietaryNote: LocaleText | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  courses: Array<{
    _key: string;
    title: LocaleString | null;
    items: LocaleStringList | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: menuBySlugQuery
// Query: *[_type == "menu" && slug.current == $slug][0] {    _id,  title,  slug,  format,  summary,  pricePerPerson,  priceNote,  minGuests,  maxGuests,  leadTimeDays,  includes,  excludes,  dietaryNote,  image,    courses[]{    _key,    title,    items  }}
export type MenuBySlugQueryResult = {
  _id: string;
  title: LocaleString | null;
  slug: Slug;
  format: "apero" | "breakfast" | "buffet" | "lunch" | "seated";
  summary: LocaleText | null;
  pricePerPerson: number;
  priceNote: LocaleString | null;
  minGuests: number;
  maxGuests: number | null;
  leadTimeDays: number;
  includes: LocaleStringList | null;
  excludes: LocaleStringList | null;
  dietaryNote: LocaleText | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  courses: Array<{
    _key: string;
    title: LocaleString | null;
    items: LocaleStringList | null;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: menuSlugsQuery
// Query: *[_type == "menu" && defined(slug.current)]{  "slug": slug.current}
export type MenuSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: lib/sanity/queries.ts
// Variable: siteDetailsQuery
// Query: *[_id == "siteSettings"][0] {  contact,  legal,  socialLinks}
export type SiteDetailsQueryResult =
  | {
      contact: null;
      legal: null;
      socialLinks: null;
    }
  | {
      contact: {
        street?: string;
        postalCode?: string;
        city?: string;
        region?: string;
        country?: string;
        phone?: string;
        email?: string;
      } | null;
      legal: {
        companyName?: string;
        enterpriseNumber?: string;
        vatNumber?: string;
        legalForm?: string;
      } | null;
      socialLinks: {
        instagram?: string;
        facebook?: string;
      } | null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_id == "homePage"][0] {  heroImage { ..., "lqip": asset->metadata.lqip },  eventsImage,  coffeeImage}
export type HomePageQueryResult =
  | {
      heroImage: null;
      eventsImage: null;
      coffeeImage: null;
    }
  | {
      heroImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        lqip: string | null;
      } | null;
      eventsImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      coffeeImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "article" && language == $language] | order(publishedAt desc) {\n  \n  _id,\n  title,\n  slug,\n  publishedAt,\n  excerpt,\n  mainImage,\n  author->{ name },\n  categories[]->{ title }\n\n}': ArticlesQueryResult;
    '*[_type == "article" && language == $language && slug.current == $slug][0] {\n  \n  _id,\n  title,\n  slug,\n  publishedAt,\n  excerpt,\n  mainImage,\n  author->{ name },\n  categories[]->{ title }\n,\n  body\n}': ArticleBySlugQueryResult;
    '*[_type == "article" && language == $language && defined(slug.current)]{\n  "slug": slug.current\n}': ArticleSlugsQueryResult;
    '*[_type == "menu"] | order(pricePerPerson asc) {\n  \n  _id,\n  title,\n  slug,\n  format,\n  summary,\n  pricePerPerson,\n  priceNote,\n  minGuests,\n  maxGuests,\n  leadTimeDays,\n  includes,\n  excludes,\n  dietaryNote,\n  image\n,\n  \n  courses[]{\n    _key,\n    title,\n    items\n  }\n\n}': MenusQueryResult;
    '*[_type == "menu" && slug.current == $slug][0] {\n  \n  _id,\n  title,\n  slug,\n  format,\n  summary,\n  pricePerPerson,\n  priceNote,\n  minGuests,\n  maxGuests,\n  leadTimeDays,\n  includes,\n  excludes,\n  dietaryNote,\n  image\n,\n  \n  courses[]{\n    _key,\n    title,\n    items\n  }\n\n}': MenuBySlugQueryResult;
    '*[_type == "menu" && defined(slug.current)]{\n  "slug": slug.current\n}': MenuSlugsQueryResult;
    '*[_id == "siteSettings"][0] {\n  contact,\n  legal,\n  socialLinks\n}': SiteDetailsQueryResult;
    '*[_id == "homePage"][0] {\n  heroImage { ..., "lqip": asset->metadata.lqip },\n  eventsImage,\n  coffeeImage\n}': HomePageQueryResult;
  }
}
