import type { Metadata } from "next";
import {
  DEFAULT_LOCALE,
  INTL_LOCALE,
  isLocale,
  LOCALES,
  OG_LOCALE,
  stripLocale,
  withLocale,
  type Locale,
} from "./i18n/config";
import { getDictionary, type Dictionary } from "./i18n/dictionaries";
import { siteConfig } from "./site";

/**
 * Schema.org and Open Graph both insist on absolute URLs. Canonicals don't —
 * they resolve against `metadataBase` in the root layout — so page metadata
 * can keep passing plain route paths.
 */
export function absoluteUrl(path: string) {
  return new URL(path, siteConfig.url).toString();
}

/**
 * Every route exists in three languages, so each one has to say so — otherwise
 * the French and Dutch versions of the same page read as duplicates competing
 * for the same query.
 *
 * `x-default` points at French: it is what a search engine shows when it has no
 * better signal, and it is the language the business actually operates in.
 *
 * Takes the route *without* a locale prefix ("/shop", not "/fr/shop"), because
 * the caller has one page and this is the thing that knows there are three of
 * it. `canonical` is the current language's own URL — a page is never the
 * canonical of its translation.
 */
export function languageAlternates(path: string, locale: Locale) {
  const bare = stripLocale(path);

  return {
    canonical: withLocale(bare, locale),
    languages: {
      ...Object.fromEntries(
        LOCALES.map((other) => [INTL_LOCALE[other], withLocale(bare, other)]),
      ),
      "x-default": withLocale(bare, DEFAULT_LOCALE),
    },
  };
}

/** The `<title>` the root layout's template would produce for a bare title. */
export function fullTitle(title: string) {
  return `${title} — ${siteConfig.name}`;
}

/**
 * The pages that have their own entry in the dictionaries under `meta`.
 *
 * `fallback` lives in the same section but is not a page — it holds the
 * sentences the content-driven routes use when Shopify or Sanity gives them
 * nothing to describe.
 */
export type MetaKey = Exclude<keyof Dictionary["meta"], "fallback">;

export type SeoImage = {
  url: string;
  alt: string;
};

/**
 * The site-wide share card drawn by app/opengraph-image.tsx, which imports
 * these back so the route and the metadata can't describe different images.
 *
 * It has to be named explicitly rather than left to the file convention: a
 * page that exports its own `openGraph` *replaces* the parent's instead of
 * merging with it, so anything using `pageMetadata` would otherwise ship with
 * no card at all.
 */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;
export const OG_IMAGE_ALT = `${siteConfig.name} — traiteur and catering in Brussels`;
const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  alt: OG_IMAGE_ALT,
  ...OG_IMAGE_SIZE,
};

type PageSeo = {
  /** Bare page title. The root layout appends " — Moment" to it. */
  title: string;
  description?: string;
  /** Route path — becomes the canonical and og:url. */
  path: string;
  keywords?: readonly string[];
  /**
   * Social preview. Omit to fall through to the site-wide card generated by
   * app/opengraph-image.tsx.
   */
  image?: SeoImage | null;
  type?: "website" | "article";
  /** Transactional and account routes — real pages, but nothing to index. */
  noindex?: boolean;
  publishedTime?: string;
  modifiedTime?: string;
  /**
   * The language this page is being rendered in. Optional only so the routes
   * that have not been converted to `generateMetadata` yet still compile —
   * every page should pass it, because without it the canonical and the
   * og:locale both claim the page is French.
   */
  locale?: Locale;
};

/**
 * One shape for every page's metadata: canonical, Open Graph and Twitter card
 * derived from the same title and description, so the three can't drift.
 */
export function pageMetadata({
  title,
  description = siteConfig.description,
  path,
  keywords,
  image,
  type = "website",
  noindex = false,
  publishedTime,
  modifiedTime,
  locale = DEFAULT_LOCALE,
}: PageSeo): Metadata {
  const heading = fullTitle(title);
  const url = absoluteUrl(withLocale(stripLocale(path), locale));

  const ogImage = image
    ? { url: image.url, alt: image.alt }
    : DEFAULT_OG_IMAGE;

  // Keys are spread in only when they have a value. Setting one to `undefined`
  // is not the same as leaving it out: an explicit key overrides what the root
  // layout resolved, which silently drops the googleBot snippet directives.
  return {
    title,
    description,
    ...(keywords ? { keywords: [...keywords] } : {}),
    alternates: languageAlternates(path, locale),
    // Crawlers still follow the links out of a noindex page — that's how they
    // reach the catalogue from a shared cart URL.
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type,
      title: heading,
      description,
      url,
      siteName: siteConfig.name,
      locale: OG_LOCALE[locale],
      images: [ogImage],
      ...(type === "article" ? { publishedTime, modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: heading,
      description,
      images: [ogImage],
    },
  };
}

/**
 * A page's SEO, as the `generateMetadata` export it has to be now that every
 * route exists in three languages.
 *
 * Static `metadata` cannot see the route params, so a page declaring it that
 * way has no idea which language it is being rendered in — it would canonical
 * every translation back to the French URL and tell search engines the Dutch
 * and English pages are duplicates not worth indexing.
 *
 * The title, description and keywords come from the dictionary under `key`
 * rather than being passed in. They were literals until every page shipped in
 * three languages and all three kept serving the English ones — which is the
 * text Google actually prints in a result, so it was the least visible and
 * most expensive thing left untranslated.
 *
 * Keywords are translated rather than shared. A French page ranking on
 * "catering Brussels" instead of "traiteur Bruxelles" is the whole multilingual
 * exercise wasted.
 */
export function localizedMetadata(
  key: MetaKey,
  options: Pick<PageSeo, "path"> &
    Partial<Pick<PageSeo, "noindex" | "image" | "type">>,
) {
  return async function generateMetadata({
    params,
  }: {
    params: Promise<{ lang: string }>;
  }): Promise<Metadata> {
    const { lang } = await params;
    const locale = isLocale(lang) ? lang : DEFAULT_LOCALE;
    const dict = await getDictionary(locale);
    const meta = dict.meta[key];

    return pageMetadata({
      ...options,
      locale,
      title: meta.title,
      description: meta.description,
      keywords: "keywords" in meta ? meta.keywords : undefined,
    });
  };
}

/** Metadata for a page whose record went missing — never indexable. */
export function notFoundMetadata(title = "Not found"): Metadata {
  return {
    title,
    robots: { index: false, follow: true },
  };
}

/**
 * Trims a body of copy down to something that reads as a whole sentence in a
 * SERP snippet, rather than a hard 160-character cut mid-word.
 */
export function toDescription(text: string | undefined | null, limit = 160) {
  const clean = text?.replace(/\s+/g, " ").trim();
  if (!clean) return undefined;
  if (clean.length <= limit) return clean;

  const cut = clean.slice(0, limit);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > limit * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\s]+$/, "")}…`;
}
