import type { Metadata } from "next";
import { siteConfig } from "./site";

/**
 * Schema.org and Open Graph both insist on absolute URLs. Canonicals don't —
 * they resolve against `metadataBase` in the root layout — so page metadata
 * can keep passing plain route paths.
 */
export function absoluteUrl(path: string) {
  return new URL(path, siteConfig.url).toString();
}

/**
 * Belgian English. The site ships single-locale; once the fr/nl copy exists
 * this becomes a per-route value and `alternates.languages` gets filled in.
 * Pointing hreflang at translations that don't exist yet is worse than having
 * none, so nothing is emitted until the copy lands. See siteConfig.locales.
 */
export const OG_LOCALE = "en_BE";

/** The `<title>` the root layout's template would produce for a bare title. */
export function fullTitle(title: string) {
  return `${title} — ${siteConfig.name}`;
}

export type SeoImage = {
  url: string;
  alt: string;
};

/**
 * The site-wide share card drawn by app/opengraph-image.tsx, which imports
 * these back so the route and the metadata can't describe different images.
 *
 * It has to be named explicitly rather than left to the file convention: a
 * page that exports its own `openGraph` *replaces* the parent's instead of
 * merging with it, so anything using `pageMetadata` would otherwise ship with
 * no card at all.
 */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;
export const OG_IMAGE_ALT = `${siteConfig.name} — traiteur and catering in Brussels`;
const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  alt: OG_IMAGE_ALT,
  ...OG_IMAGE_SIZE,
};

type PageSeo = {
  /** Bare page title. The root layout appends " — Moment" to it. */
  title: string;
  description?: string;
  /** Route path — becomes the canonical and og:url. */
  path: string;
  keywords?: readonly string[];
  /**
   * Social preview. Omit to fall through to the site-wide card generated by
   * app/opengraph-image.tsx.
   */
  image?: SeoImage | null;
  type?: "website" | "article";
  /** Transactional and account routes — real pages, but nothing to index. */
  noindex?: boolean;
  publishedTime?: string;
  modifiedTime?: string;
};

/**
 * One shape for every page's metadata: canonical, Open Graph and Twitter card
 * derived from the same title and description, so the three can't drift.
 */
export function pageMetadata({
  title,
  description = siteConfig.description,
  path,
  keywords,
  image,
  type = "website",
  noindex = false,
  publishedTime,
  modifiedTime,
}: PageSeo): Metadata {
  const heading = fullTitle(title);
  const url = absoluteUrl(path);

  const ogImage = image
    ? { url: image.url, alt: image.alt }
    : DEFAULT_OG_IMAGE;

  // Keys are spread in only when they have a value. Setting one to `undefined`
  // is not the same as leaving it out: an explicit key overrides what the root
  // layout resolved, which silently drops the googleBot snippet directives.
  return {
    title,
    description,
    ...(keywords ? { keywords: [...keywords] } : {}),
    alternates: { canonical: path },
    // Crawlers still follow the links out of a noindex page — that's how they
    // reach the catalogue from a shared cart URL.
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type,
      title: heading,
      description,
      url,
      siteName: siteConfig.name,
      locale: OG_LOCALE,
      images: [ogImage],
      ...(type === "article" ? { publishedTime, modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: heading,
      description,
      images: [ogImage],
    },
  };
}

/** Metadata for a page whose record went missing — never indexable. */
export function notFoundMetadata(title = "Not found"): Metadata {
  return {
    title,
    robots: { index: false, follow: true },
  };
}

/**
 * Trims a body of copy down to something that reads as a whole sentence in a
 * SERP snippet, rather than a hard 160-character cut mid-word.
 */
export function toDescription(text: string | undefined | null, limit = 160) {
  const clean = text?.replace(/\s+/g, " ").trim();
  if (!clean) return undefined;
  if (clean.length <= limit) return clean;

  const cut = clean.slice(0, limit);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > limit * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\s]+$/, "")}…`;
}
